export default [
  {
    district: 'Karachi',
    city: 'Karachi',
    lat: 24.86,
    lng: 67.01,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 14835000,
  },
  {
    district: 'Lahore',
    city: 'Lahore',
    lat: 31.5497,
    lng: 74.3436,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 11021000,
  },
  {
    district: 'Faisalabad',
    city: 'Faisalabad',
    lat: 31.418,
    lng: 73.079,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 3203846,
  },
  {
    district: 'Rawalpindi',
    city: 'Rawalpindi',
    lat: 33.6007,
    lng: 73.0679,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 2098231,
  },
  {
    district: 'Gujranwala',
    city: 'Gujranwala',
    lat: 32.15,
    lng: 74.1833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 2027001,
  },
  {
    district: 'Peshawar',
    city: 'Peshawar',
    lat: 34,
    lng: 71.5,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 1970042,
  },
  {
    district: 'Multan',
    city: 'Multan',
    lat: 30.1978,
    lng: 71.4711,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 1871843,
  },
  {
    district: 'Saidu Sharif',
    city: 'Saidu Sharif',
    lat: 34.75,
    lng: 72.3572,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 1860310,
  },
  {
    district: 'Hyderabad City',
    city: 'Hyderabad City',
    lat: 25.3792,
    lng: 68.3683,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 1732693,
  },
  {
    district: 'Islamabad',
    city: 'Islamabad',
    lat: 33.6989,
    lng: 73.0369,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Islāmābād',
    population: 1014825,
  },
  {
    district: 'Quetta',
    city: 'Quetta',
    lat: 30.192,
    lng: 67.007,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 1001205,
  },
  {
    district: 'Bahawalpur',
    city: 'Bahawalpur',
    lat: 29.3956,
    lng: 71.6722,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 762111,
  },
  {
    district: 'Sargodha',
    city: 'Sargodha',
    lat: 32.0836,
    lng: 72.6711,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 659862,
  },
  {
    district: 'Sialkot City',
    city: 'Sialkot City',
    lat: 32.5,
    lng: 74.5333,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 655852,
  },
  {
    district: 'Sukkur',
    city: 'Sukkur',
    lat: 27.6995,
    lng: 68.8673,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 499900,
  },
  {
    district: 'Larkana',
    city: 'Larkana',
    lat: 27.56,
    lng: 68.2264,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 490508,
  },
  {
    district: 'Chiniot',
    city: 'Chiniot',
    lat: 31.7167,
    lng: 72.9833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 477781,
  },
  {
    district: 'Shekhupura',
    city: 'Shekhupura',
    lat: 31.7083,
    lng: 74,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 473129,
  },
  {
    district: 'Jhang City',
    city: 'Jhang City',
    lat: 31.2681,
    lng: 72.3181,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 414131,
  },
  {
    district: 'Dera Ghazi Khan',
    city: 'Dera Ghazi Khan',
    lat: 30.05,
    lng: 70.6333,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 399064,
  },
  {
    district: 'Gujrat',
    city: 'Gujrat',
    lat: 32.5736,
    lng: 74.0789,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 390533,
  },
  {
    district: 'Rahimyar Khan',
    city: 'Rahimyar Khan',
    lat: 28.4202,
    lng: 70.2952,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 353203,
  },
  {
    district: 'Kasur',
    city: 'Kasur',
    lat: 31.1167,
    lng: 74.45,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 314617,
  },
  {
    district: 'Mardan',
    city: 'Mardan',
    lat: 34.1958,
    lng: 72.0447,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 300424,
  },
  {
    district: 'Mingaora',
    city: 'Mingaora',
    lat: 34.7717,
    lng: 72.36,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 279914,
  },
  {
    district: 'Nawabshah',
    city: 'Nawabshah',
    lat: 26.2442,
    lng: 68.41,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 263102,
  },
  {
    district: 'Sahiwal',
    city: 'Sahiwal',
    lat: 30.6706,
    lng: 73.1064,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 247706,
  },
  {
    district: 'Mirpur Khas',
    city: 'Mirpur Khas',
    lat: 25.5269,
    lng: 69.0111,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 236961,
  },
  {
    district: 'Okara',
    city: 'Okara',
    lat: 30.81,
    lng: 73.4597,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 232386,
  },
  {
    district: 'Mandi Burewala',
    city: 'Mandi Burewala',
    lat: 30.15,
    lng: 72.6833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 203454,
  },
  {
    district: 'Jacobabad',
    city: 'Jacobabad',
    lat: 28.2769,
    lng: 68.4514,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 200815,
  },
  {
    district: 'Saddiqabad',
    city: 'Saddiqabad',
    lat: 28.3006,
    lng: 70.1302,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 189876,
  },
  {
    district: 'Kohat',
    city: 'Kohat',
    lat: 33.5869,
    lng: 71.4414,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 170800,
  },
  {
    district: 'Muridke',
    city: 'Muridke',
    lat: 31.802,
    lng: 74.255,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 163268,
  },
  {
    district: 'Muzaffargarh',
    city: 'Muzaffargarh',
    lat: 30.0703,
    lng: 71.1933,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 163268,
  },
  {
    district: 'Khanpur',
    city: 'Khanpur',
    lat: 28.6471,
    lng: 70.662,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 160308,
  },
  {
    district: 'Gojra',
    city: 'Gojra',
    lat: 31.15,
    lng: 72.6833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 157863,
  },
  {
    district: 'Mandi Bahauddin',
    city: 'Mandi Bahauddin',
    lat: 32.5861,
    lng: 73.4917,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 157352,
  },
  {
    district: 'Abbottabad',
    city: 'Abbottabad',
    lat: 34.15,
    lng: 73.2167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 148587,
  },
  {
    district: 'Turbat',
    city: 'Turbat',
    lat: 26.0031,
    lng: 63.0544,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 147791,
  },
  {
    district: 'Dadu',
    city: 'Dadu',
    lat: 26.7319,
    lng: 67.775,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 146179,
  },
  {
    district: 'Bahawalnagar',
    city: 'Bahawalnagar',
    lat: 29.9944,
    lng: 73.2536,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 141935,
  },
  {
    district: 'Khuzdar',
    city: 'Khuzdar',
    lat: 27.8,
    lng: 66.6167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 141395,
  },
  {
    district: 'Pakpattan',
    city: 'Pakpattan',
    lat: 30.35,
    lng: 73.4,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 139525,
  },
  {
    district: 'Tando Allahyar',
    city: 'Tando Allahyar',
    lat: 25.4667,
    lng: 68.7167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 133487,
  },
  {
    district: 'Ahmadpur East',
    city: 'Ahmadpur East',
    lat: 29.1453,
    lng: 71.2617,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 128112,
  },
  {
    district: 'Vihari',
    city: 'Vihari',
    lat: 30.0419,
    lng: 72.3528,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 128034,
  },
  {
    district: 'Jaranwala',
    city: 'Jaranwala',
    lat: 31.3342,
    lng: 73.4194,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 127973,
  },
  {
    district: 'New Mirpur',
    city: 'New Mirpur',
    lat: 33.1333,
    lng: 73.75,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Azad Kashmir',
    population: 124352,
  },
  {
    district: 'Kamalia',
    city: 'Kamalia',
    lat: 30.7258,
    lng: 72.6447,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 121401,
  },
  {
    district: 'Kot Addu',
    city: 'Kot Addu',
    lat: 30.47,
    lng: 70.9644,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 120479,
  },
  {
    district: 'Nowshera',
    city: 'Nowshera',
    lat: 34.0153,
    lng: 71.9747,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 118594,
  },
  {
    district: 'Swabi',
    city: 'Swabi',
    lat: 34.1167,
    lng: 72.4667,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 115018,
  },
  {
    district: 'Khushab',
    city: 'Khushab',
    lat: 32.2917,
    lng: 72.35,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 110868,
  },
  {
    district: 'Dera Ismail Khan',
    city: 'Dera Ismail Khan',
    lat: 31.8167,
    lng: 70.9167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 109686,
  },
  {
    district: 'Chaman',
    city: 'Chaman',
    lat: 30.921,
    lng: 66.4597,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 107660,
  },
  {
    district: 'Charsadda',
    city: 'Charsadda',
    lat: 34.1453,
    lng: 71.7308,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 105414,
  },
  {
    district: 'Kandhkot',
    city: 'Kandhkot',
    lat: 28.4,
    lng: 69.3,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 105011,
  },
  {
    district: 'Chishtian',
    city: 'Chishtian',
    lat: 29.7958,
    lng: 72.8578,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 101659,
  },
  {
    district: 'Hasilpur',
    city: 'Hasilpur',
    lat: 29.6967,
    lng: 72.5542,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 99171,
  },
  {
    district: 'Attock Khurd',
    city: 'Attock Khurd',
    lat: 33.7667,
    lng: 72.3667,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 97374,
  },
  {
    district: 'Muzaffarabad',
    city: 'Muzaffarabad',
    lat: 34.37,
    lng: 73.4711,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Azad Kashmir',
    population: 96000,
  },
  {
    district: 'Mianwali',
    city: 'Mianwali',
    lat: 32.5853,
    lng: 71.5436,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 95007,
  },
  {
    district: 'Jalalpur Jattan',
    city: 'Jalalpur Jattan',
    lat: 32.7667,
    lng: 74.2167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 90130,
  },
  {
    district: 'Bhakkar',
    city: 'Bhakkar',
    lat: 31.6333,
    lng: 71.0667,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 88472,
  },
  {
    district: 'Zhob',
    city: 'Zhob',
    lat: 31.3417,
    lng: 69.4486,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 88356,
  },
  {
    district: 'Dipalpur',
    city: 'Dipalpur',
    lat: 30.6708,
    lng: 73.6533,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 87176,
  },
  {
    district: 'Kharian',
    city: 'Kharian',
    lat: 32.811,
    lng: 73.865,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 85765,
  },
  {
    district: 'Mian Channun',
    city: 'Mian Channun',
    lat: 30.4397,
    lng: 72.3544,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 82586,
  },
  {
    district: 'Bhalwal',
    city: 'Bhalwal',
    lat: 32.2653,
    lng: 72.9028,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 82556,
  },
  {
    district: 'Jamshoro',
    city: 'Jamshoro',
    lat: 25.4283,
    lng: 68.2822,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 80000,
  },
  {
    district: 'Pattoki',
    city: 'Pattoki',
    lat: 31.0214,
    lng: 73.8528,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 77210,
  },
  {
    district: 'Harunabad',
    city: 'Harunabad',
    lat: 29.61,
    lng: 73.1361,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 77206,
  },
  {
    district: 'Kahror Pakka',
    city: 'Kahror Pakka',
    lat: 29.6236,
    lng: 71.9167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 76098,
  },
  {
    district: 'Toba Tek Singh',
    city: 'Toba Tek Singh',
    lat: 30.9667,
    lng: 72.4833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 75943,
  },
  {
    district: 'Samundri',
    city: 'Samundri',
    lat: 31.0639,
    lng: 72.9611,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 73911,
  },
  {
    district: 'Shakargarh',
    city: 'Shakargarh',
    lat: 32.2628,
    lng: 75.1583,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 73160,
  },
  {
    district: 'Sambrial',
    city: 'Sambrial',
    lat: 32.475,
    lng: 74.3522,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 71766,
  },
  {
    district: 'Shujaabad',
    city: 'Shujaabad',
    lat: 29.8803,
    lng: 71.295,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 70595,
  },
  {
    district: 'Hujra Shah Muqim',
    city: 'Hujra Shah Muqim',
    lat: 30.7408,
    lng: 73.8219,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 70204,
  },
  {
    district: 'Kabirwala',
    city: 'Kabirwala',
    lat: 30.4068,
    lng: 71.8667,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 70123,
  },
  {
    district: 'Mansehra',
    city: 'Mansehra',
    lat: 34.3333,
    lng: 73.2,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 69085,
  },
  {
    district: 'Lala Musa',
    city: 'Lala Musa',
    lat: 32.7006,
    lng: 73.9558,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 67283,
  },
  {
    district: 'Chunian',
    city: 'Chunian',
    lat: 30.9639,
    lng: 73.9803,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 64386,
  },
  {
    district: 'Nankana Sahib',
    city: 'Nankana Sahib',
    lat: 31.4492,
    lng: 73.7124,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 63073,
  },
  {
    district: 'Bannu',
    city: 'Bannu',
    lat: 32.9889,
    lng: 70.6056,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 62191,
  },
  {
    district: 'Pasrur',
    city: 'Pasrur',
    lat: 32.2681,
    lng: 74.6675,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 58644,
  },
  {
    district: 'Timargara',
    city: 'Timargara',
    lat: 34.8281,
    lng: 71.8408,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 58050,
  },
  {
    district: 'Parachinar',
    city: 'Parachinar',
    lat: 33.8992,
    lng: 70.1008,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 55685,
  },
  {
    district: 'Chenab Nagar',
    city: 'Chenab Nagar',
    lat: 31.75,
    lng: 72.9167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 53965,
  },
  {
    district: 'Gwadar',
    city: 'Gwadar',
    lat: 25.1264,
    lng: 62.3225,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 51901,
  },
  {
    district: 'Abdul Hakim',
    city: 'Abdul Hakim',
    lat: 30.5522,
    lng: 72.1278,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 51494,
  },
  {
    district: 'Hassan Abdal',
    city: 'Hassan Abdal',
    lat: 33.8195,
    lng: 72.689,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 50044,
  },
  {
    district: 'Tank',
    city: 'Tank',
    lat: 32.2167,
    lng: 70.3833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 44996,
  },
  {
    district: 'Hangu',
    city: 'Hangu',
    lat: 33.5281,
    lng: 71.0572,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 39766,
  },
  {
    district: 'Risalpur Cantonment',
    city: 'Risalpur Cantonment',
    lat: 34.0049,
    lng: 71.9989,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 36653,
  },
  {
    district: 'Karak',
    city: 'Karak',
    lat: 33.1167,
    lng: 71.0833,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 35844,
  },
  {
    district: 'Kundian',
    city: 'Kundian',
    lat: 32.4522,
    lng: 71.4718,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: 35406,
  },
  {
    district: 'Umarkot',
    city: 'Umarkot',
    lat: 25.3614,
    lng: 69.7361,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: 35059,
  },
  {
    district: 'Chitral',
    city: 'Chitral',
    lat: 35.8511,
    lng: 71.7889,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 31100,
  },
  {
    district: 'Dainyor',
    city: 'Dainyor',
    lat: 35.9206,
    lng: 74.3783,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Gilgit-Baltistan',
    population: 25000,
  },
  {
    district: 'Kulachi',
    city: 'Kulachi',
    lat: 31.9286,
    lng: 70.4592,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: 24738,
  },
  {
    district: 'Kalat',
    city: 'Kalat',
    lat: 29.0258,
    lng: 66.59,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: 22879,
  },
  {
    district: 'Kotli',
    city: 'Kotli',
    lat: 33.5156,
    lng: 73.9019,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Azad Kashmir',
    population: 21462,
  },
  {
    district: 'Gilgit',
    city: 'Gilgit',
    lat: 35.9208,
    lng: 74.3144,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Gilgit-Baltistan',
    population: 8851,
  },
  {
    district: 'Narowal',
    city: 'Narowal',
    lat: 32.102,
    lng: 74.873,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Khairpur Mir’s',
    city: 'Khairpur Mir’s',
    lat: 27.5295,
    lng: 68.7592,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Khanewal',
    city: 'Khanewal',
    lat: 30.3017,
    lng: 71.9321,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Jhelum',
    city: 'Jhelum',
    lat: 32.9333,
    lng: 73.7333,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Haripur',
    city: 'Haripur',
    lat: 33.9942,
    lng: 72.9333,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Shikarpur',
    city: 'Shikarpur',
    lat: 27.9556,
    lng: 68.6382,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Rawala Kot',
    city: 'Rawala Kot',
    lat: 33.8578,
    lng: 73.7604,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Azad Kashmir',
    population: '',
  },
  {
    district: 'Hafizabad',
    city: 'Hafizabad',
    lat: 32.0709,
    lng: 73.688,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Lodhran',
    city: 'Lodhran',
    lat: 29.5383,
    lng: 71.6333,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Malakand',
    city: 'Malakand',
    lat: 34.5656,
    lng: 71.9304,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Attock City',
    city: 'Attock City',
    lat: 33.7667,
    lng: 72.3598,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Batgram',
    city: 'Batgram',
    lat: 34.6796,
    lng: 73.0263,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Matiari',
    city: 'Matiari',
    lat: 25.5971,
    lng: 68.4467,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Ghotki',
    city: 'Ghotki',
    lat: 28.0064,
    lng: 69.315,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Naushahro Firoz',
    city: 'Naushahro Firoz',
    lat: 26.8401,
    lng: 68.1227,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Alpurai',
    city: 'Alpurai',
    lat: 34.9,
    lng: 72.6556,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Bagh',
    city: 'Bagh',
    lat: 33.9803,
    lng: 73.7747,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Azad Kashmir',
    population: '',
  },
  {
    district: 'Daggar',
    city: 'Daggar',
    lat: 34.5111,
    lng: 72.4844,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Leiah',
    city: 'Leiah',
    lat: 30.9646,
    lng: 70.9444,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Tando Muhammad Khan',
    city: 'Tando Muhammad Khan',
    lat: 25.1239,
    lng: 68.5389,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Chakwal',
    city: 'Chakwal',
    lat: 32.93,
    lng: 72.85,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Badin',
    city: 'Badin',
    lat: 24.6558,
    lng: 68.8383,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Lakki',
    city: 'Lakki',
    lat: 32.6072,
    lng: 70.9123,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Rajanpur',
    city: 'Rajanpur',
    lat: 29.1041,
    lng: 70.3297,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Punjab',
    population: '',
  },
  {
    district: 'Dera Allahyar',
    city: 'Dera Allahyar',
    lat: 28.4167,
    lng: 68.1667,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Shahdad Kot',
    city: 'Shahdad Kot',
    lat: 27.8473,
    lng: 67.9068,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Pishin',
    city: 'Pishin',
    lat: 30.5833,
    lng: 67,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Sanghar',
    city: 'Sanghar',
    lat: 26.0464,
    lng: 68.9481,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Upper Dir',
    city: 'Upper Dir',
    lat: 35.2074,
    lng: 71.8768,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Thatta',
    city: 'Thatta',
    lat: 24.7461,
    lng: 67.9243,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Sindh',
    population: '',
  },
  {
    district: 'Dera Murad Jamali',
    city: 'Dera Murad Jamali',
    lat: 28.5466,
    lng: 68.2231,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Kohlu',
    city: 'Kohlu',
    lat: 29.8965,
    lng: 69.2532,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Mastung',
    city: 'Mastung',
    lat: 29.7997,
    lng: 66.8455,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Dasu',
    city: 'Dasu',
    lat: 35.2917,
    lng: 73.2906,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Khyber Pakhtunkhwa',
    population: '',
  },
  {
    district: 'Athmuqam',
    city: 'Athmuqam',
    lat: 34.5717,
    lng: 73.8972,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Azad Kashmir',
    population: '',
  },
  {
    district: 'Loralai',
    city: 'Loralai',
    lat: 30.3705,
    lng: 68.5979,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Barkhan',
    city: 'Barkhan',
    lat: 29.8977,
    lng: 69.5256,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Musa Khel Bazar',
    city: 'Musa Khel Bazar',
    lat: 30.8594,
    lng: 69.8221,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Ziarat',
    city: 'Ziarat',
    lat: 30.3814,
    lng: 67.7258,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Gandava',
    city: 'Gandava',
    lat: 28.6132,
    lng: 67.4856,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Sibi',
    city: 'Sibi',
    lat: 29.543,
    lng: 67.8773,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Dera Bugti',
    city: 'Dera Bugti',
    lat: 29.0362,
    lng: 69.1585,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Eidgah',
    city: 'Eidgah',
    lat: 35.3471,
    lng: 74.8563,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Gilgit-Baltistan',
    population: '',
  },
  {
    district: 'Uthal',
    city: 'Uthal',
    lat: 25.8072,
    lng: 66.6228,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Khuzdar',
    city: 'Khuzdar',
    lat: 27.7384,
    lng: 66.6434,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Chilas',
    city: 'Chilas',
    lat: 35.4206,
    lng: 74.0967,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Gilgit-Baltistan',
    population: '',
  },
  {
    district: 'Panjgur',
    city: 'Panjgur',
    lat: 26.9644,
    lng: 64.0903,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Gakuch',
    city: 'Gakuch',
    lat: 36.1736,
    lng: 73.7667,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Gilgit-Baltistan',
    population: '',
  },
  {
    district: 'Qila Saifullah',
    city: 'Qila Saifullah',
    lat: 30.7008,
    lng: 68.3598,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Kharan',
    city: 'Kharan',
    lat: 28.5833,
    lng: 65.4167,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Aliabad',
    city: 'Aliabad',
    lat: 36.3078,
    lng: 74.6178,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Gilgit-Baltistan',
    population: '',
  },
  {
    district: 'Awaran',
    city: 'Awaran',
    lat: 26.4568,
    lng: 65.2314,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
  {
    district: 'Dalbandin',
    city: 'Dalbandin',
    lat: 28.8885,
    lng: 64.4062,
    country: 'Pakistan',
    countryCode: 'PK',
    captial: 'Balochistān',
    population: '',
  },
];
